### ISSUE TITLE
Invalid error message throws when LDAP entry is not present.

### ISSUE THREAD

**Issue by pathberiya** [wso2-extensions/esb-connector-ldap#16]
According to the "makeSureOnlyOneMatch()" method, when LDAP entry is not found, it returns following error. 

throw new NamingException("Multiple objects for the searched target have been found. Try to change onlyOneReference option");

We need fix to throw proper error

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3506
