### ISSUE TITLE
Add support for anonymous bind

### ISSUE THREAD

**Issue by hr15a** [wso2-extensions/esb-connector-ldap#50]
## Description

Connector do not support [anonymous bind](https://ldapwiki.com/wiki/Anonymous%20bind) for LDAP connections.

This authentication method allows LDAP request without authentication and is useful when policy on LDAP server is :
* allow anonymous bind
* forbid technical account

The [JNDI APIs](https://directory.apache.org/api/user-guide/2.2-binding-unbinding.html) used by connector supports anonymous bind

## Suggested Labels
enhancement,"Type/New Feature"

## Affected Product Version

* Integration Studio 8.0.0
* LDAP connector 1.0.11

## OS, DB, other environment details and versions

* Ubuntu Linux (but all platforms are affected)

## Steps to reproduce

1. Create an ESB project with LDAP connection
2. Configure LDAP connection without `<securityPrincipal>` attributes

## Related Issues

https://support.wso2.com/jira/browse/SMILEDEV-84

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3505
